### ISSUE TITLE
Things left for the release

### ISSUE THREAD

**Issue by iswarmondal** [NetSepio/ChromiumExtension#24]
### Here are the things left to be done before the release (also take a look at the individual issues)

- [x] Integrate the API for letting the user submit a review ( #15 )
- [x] Show wallet details ( #22 )
- [x] Improve the UI ( #14 )
- [x] Lock the wallet by default ( #21 )
- [x] Setup private route ( #17 )

**Comment by iswarmondal** [comment]
Done
